name: Github Pages Deploy

on:
  push:
    branches:
      - "main"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and Build
        working-directory: ./test1
        run: npm install && npm run build && cp dist/test1/index.html dist/test1/404.html
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: test1/dist/test1 # The folder the action should deploy.        

# name: GitHub Pages

# on:
#   push:
#     branches:
#     - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Setup Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14.18.0'

#     - name: Install dependencies
#       run: npm install

#     # - name: Run tests
#     #   run: npm run test:headless

#     - name: Build
#       run: npm run build

#     - name: Deploy
#       if: success()
#       uses: JamesIves/github-pages-deploy-action@4.1.1
#       with:
#         branch: gh-pages # The branch the action should deploy to.
#         folder: ./dist/test1 # The folder the action should deploy. 
